# Generated by Django 6.0.4 on 2026-04-20 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportscheme',
            name='scheme_type',
        ),
        migrations.AddField(
            model_name='supportscheme',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='suitability_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crop',
            name='yield_estimate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supportscheme',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supportscheme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
