# Generated by Django 6.0.4 on 2026-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fertilizers', 'Fertilizers'), ('Seeds', 'Seeds & Planting Material'), ('Pesticides', 'Pesticides & Insecticides'), ('Tools', 'Farming Tools & Equipment'), ('Organic', 'Organic Products'), ('Irrigation', 'Irrigation & Sprinklers'), ('Soil', 'Soil Testing Kits'), ('AnimalFeed', 'Animal Feed & Supplements')], max_length=50),
        ),
    ]
