# Generated by Django 6.0.4 on 2026-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_rating_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fertilizers', 'Fertilizers'), ('Seeds', 'Seeds & Planting Material'), ('Pesticides', 'Pesticides & Insecticides'), ('Tools', 'Farming Tools & Equipment'), ('Organic', 'Organic Products'), ('Irrigation', 'Irrigation & Sprinklers'), ('Soil', 'Soil Testing Kits')], max_length=50),
        ),
    ]
