# Generated by Django 6.0.4 on 2026-04-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_transaction_id_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_id', models.CharField(max_length=12, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_name', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='quality',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fertilizers', 'Fertilizers'), ('Seeds', 'Seeds & Planting Material'), ('Pesticides', 'Pesticides & Insecticides'), ('Tools', 'Farming Tools & Equipment'), ('Organic', 'Organic Products'), ('Irrigation', 'Irrigation & Sprinklers'), ('Soil', 'Soil Testing Kits'), ('Marketplace', 'Farmers Marketplace')], max_length=50),
        ),
    ]
