# Generated by Django 6.0.4 on 2026-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_banktransaction_marketlisting_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description shown in the store', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Upload product image directly (overrides URL above)', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Public URL for product image', max_length=500, null=True),
        ),
    ]
