# Generated by Django 6.0.4 on 2026-04-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='request_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('EXCHANGE', 'Exchange')], default='REFUND', max_length=10),
        ),
    ]
