# Generated by Django 6.0.4 on 2026-04-28 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_refundrequest_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('optimal_temperature', models.FloatField(help_text='Optimal temperature in Celsius')),
                ('temperature_tolerance', models.FloatField(default=2.0, help_text='Temperature tolerance ±°C')),
                ('optimal_humidity', models.FloatField(help_text='Optimal humidity percentage')),
                ('humidity_tolerance', models.FloatField(default=5.0, help_text='Humidity tolerance ±%')),
                ('optimal_moisture', models.FloatField(help_text='Optimal soil moisture percentage')),
                ('moisture_tolerance', models.FloatField(default=10.0, help_text='Moisture tolerance ±%')),
                ('light_hours', models.IntegerField(default=16, help_text='Required light hours per day')),
                ('light_intensity', models.IntegerField(default=300, help_text='Light intensity in µmol/m²/s')),
                ('growth_stage_days', models.JSONField(default=dict, help_text='Days per growth stage')),
                ('water_consumption', models.FloatField(default=1.0, help_text='Daily water consumption in liters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Crop Environment',
                'verbose_name_plural': 'Crop Environments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('chamber', 'Growth Chamber'), ('irrigation', 'Irrigation System'), ('sensor', 'Sensor Node')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('mqtt_topic', models.CharField(blank=True, max_length=200)),
                ('configuration', models.JSONField(default=dict, help_text='Device configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IoT Device',
                'verbose_name_plural': 'IoT Devices',
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('days_of_week', models.JSONField(default=list, help_text='Days of week [1,2,3,4,5]')),
                ('moisture_threshold', models.FloatField(blank=True, help_text='Only irrigate if moisture below this', null=True)),
                ('skip_rain', models.BooleanField(default=True, help_text='Skip irrigation on rainy days')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_schedules', to='core.iotdevice')),
            ],
            options={
                'verbose_name': 'Irrigation Schedule',
                'verbose_name_plural': 'Irrigation Schedules',
                'ordering': ['device', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ChamberControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('manual_control', 'Manual Control'), ('auto_control', 'Automatic Control'), ('schedule_trigger', 'Schedule Trigger'), ('emergency_stop', 'Emergency Stop'), ('system_error', 'System Error'), ('calibration', 'Calibration')], max_length=20)),
                ('description', models.TextField()),
                ('target_actuator', models.CharField(blank=True, max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='system', help_text='Source of the action', max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_logs', to='core.iotdevice')),
            ],
            options={
                'verbose_name': 'Control Log',
                'verbose_name_plural': 'Control Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='core_chambe_device__4ecc9f_idx'), models.Index(fields=['action_type', '-timestamp'], name='core_chambe_action__70f46a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActuatorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator_type', models.CharField(choices=[('water_pump', 'Water Pump'), ('cooling_fan', 'Cooling Fan'), ('heater', 'Heater'), ('grow_light', 'Grow Light'), ('humidifier', 'Humidifier'), ('ventilation', 'Ventilation')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('power_level', models.IntegerField(default=0, help_text='Power level 0-100%')),
                ('control_mode', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('scheduled', 'Scheduled')], default='auto', max_length=20)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuator_states', to='core.iotdevice')),
            ],
            options={
                'verbose_name': 'Actuator State',
                'verbose_name_plural': 'Actuator States',
                'ordering': ['device', 'actuator_type'],
                'unique_together': {('device', 'actuator_type')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('soil_moisture', 'Soil Moisture'), ('light', 'Light Intensity'), ('ph', 'pH Level'), ('ec', 'Electrical Conductivity')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(help_text='Measurement unit (°C, %, lux, etc.)', max_length=10)),
                ('quality_score', models.FloatField(default=100.0, help_text='Data quality score 0-100')),
                ('is_anomaly', models.BooleanField(default=False, help_text='Flagged as anomalous reading')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='core.iotdevice')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'sensor_type', '-timestamp'], name='core_sensor_device__84b639_idx'), models.Index(fields=['timestamp'], name='core_sensor_timesta_24592c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sensor_failure', 'Sensor Failure'), ('actuator_failure', 'Actuator Failure'), ('network_disconnected', 'Network Disconnected'), ('power_failure', 'Power Failure'), ('environmental_extreme', 'Environmental Extreme'), ('maintenance_required', 'Maintenance Required'), ('security_breach', 'Security Breach')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.iotdevice')),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='core_system_severit_d6e813_idx'), models.Index(fields=['is_resolved', '-created_at'], name='core_system_is_reso_be5cc7_idx')],
            },
        ),
    ]
